84 slicing tambah pertanyaan
HarsaEdu/harsa-frontend pull request #100
Opened 2023-12-01 10:36 UTC by fannyrahmasari

Video Demo
https://drive.google.com/file/d/1XOIzkGsUVWv5lmX2RhLmPdomekp37IuD/view?usp=sharing

<img width="960" alt="Screenshot 2023-12-01 173330" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/8a216b6e-ae67-4abb-b7d8-5830dae6c944">

<img width="960" alt="Screenshot 2023-12-01 173358" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/b2a35684-4660-4324-8208-e99c66639aae">

<img width="960" alt="Screenshot 2023-12-01 173432" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/453dfaf8-8306-4c0e-9107-156c4627b96e">

2023-12-01 13:31 UTC, KokoYuardiA reviewed
minta diubah yang alert dong, sesuaikan sama yang di figma (kasih close atau x buat nutup alert)

2023-12-01 13:31 UTC, KokoYuardiA commented on src/pages/tambah-kuis/createQuiz.jsx
> +function handleClick(){
ubah alert, sesuaikan sama di figma

2023-12-01 15:13 UTC, cha-chaham requested changes

2023-12-01 15:13 UTC, cha-chaham commented on src/pages/tambah-kuis/createQuiz.jsx
> +                    <img src={DeleteIcon} alt="DeleteIcon" />
Delete Iconnya di figma gak pake bg-color mba
![image](https://github.com/HarsaEdu/harsa-frontend/assets/63897235/7d9650cb-3893-4a7e-b95a-a09cced72484)

2023-12-02 10:21 UTC, dimdimah commented
pull request yang ini sudah di revisi kah mba fanny?

2023-12-04 08:51 UTC, fannyrahmasari commented
video demo :
https://drive.google.com/file/d/1oxrz-KRafmnst-hOV9_UAsY8gjI3pn4F/view?usp=sharing

menambahkan silang ( x ) untuk close pada alert
<img width="960" alt="Screenshot 2023-12-04 154321" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/5a5469bd-98b5-40f7-ad00-05b6f555e8c9">

delete icon tidak menggunakan background dan menerapkan ukuran text milik tailwind 
<img width="685" alt="Screenshot 2023-12-04 154457" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/d50cfbc4-5fed-422d-8502-b9baecf767af">
<img width="613" alt="Screenshot 2023-12-04 154523" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/936f727f-93dd-4708-bcd7-1f0c45c823ef">

setiap radio button di klik maka akan muncul ceklis, dan setiap tombol silang di klik maka akan menghapus kuis
<img width="960" alt="Screenshot 2023-12-04 154647" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/bda39060-3089-4b74-aa95-80d40def0497">

2023-12-04 16:47 UTC, merged