feat: add page AddSubscription, AddSubscriptionPackage, EditSubscript…
HarsaEdu/harsa-frontend pull request #133
Opened 2023-12-06 15:50 UTC by fannyrahmasari

- Slicing halaman pembayaran ( langganan )

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/a8aebc79-4d12-48e2-a122-848e8fc35439

- Menambahkan fungsi onClick pada tombol tambah paket, serta memberikan validasi pada form tambah paket

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/d253c30d-d706-4a86-bd63-3e41fd81d4b7

<img width="716" alt="Screenshot 2023-12-06 224113" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/a894c5e7-f5c8-4529-a472-ca41ed6931d3">

- Menambahkan alert Sukses Tambah  Data paket  Langganan

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/5bc69a5e-8398-49d7-abf9-5c962335ee84

- Menambahkan alert cofirmasi untuk delete data

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/606b5914-b6f0-45e4-b673-3ce330edde66

- Menambahkan onClick pada columns untuk bisa edit data

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/5f4efa72-8047-4768-a5a3-6358faad3d03

- Menambahkan alert confirmasi untuk simpan data

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/7c324a4a-cf5e-42fb-b369-489126d07542

2023-12-06 16:40 UTC, KokoYuardiA requested changes
input file pakai inputFile.jsx punya mas Charlie ya, walaupun nggak sama kaya Figma
nanti di figma aku minta ganti

2023-12-06 16:40 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/editPaketLangganan.jsx
> +                                    <div className="border border-black border-dashed w-full flex flex-col justify-center items-center p-5 font-poppins font-semibold text-[#A2D2FF] text-lg">
ini ganti jadi inputFile.jsx nya mas Charlie

2023-12-06 16:40 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/editPaketLangganan.jsx
> +                                    <div className="border border-black border-dashed w-full flex flex-col justify-center items-center p-5 font-poppins font-semibold text-[#A2D2FF] text-lg">
pokoknya input file gambar pakai inputFile.jsx

2023-12-06 16:40 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/tambahPaketLangganan.jsx
> +                                <div className="w-full h-56 border border-black rounded-lg flex justify-center items-center p-4">
ganti ke inputFile.jsx

2023-12-06 16:51 UTC, fannyrahmasari commented on src/pages/admin/pembayaran/tambahPaketLangganan.jsx
> +                                <div className="w-full h-56 border border-black rounded-lg flex justify-center items-center p-4">
okee mas

2023-12-06 17:15 UTC, fannyrahmasari commented on src/pages/admin/pembayaran/tambahPaketLangganan.jsx
> +                                <div className="w-full h-56 border border-black rounded-lg flex justify-center items-center p-4">
seperti ini mas koko?
<img width="492" alt="Screenshot 2023-12-07 001152" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/84df3f65-1738-4312-9122-704232cd0ead">

2023-12-06 17:16 UTC, fannyrahmasari commented
- tambah input harga, kelupaan
<img width="960" alt="Screenshot 2023-12-07 001627" src="https://github.com/HarsaEdu/harsa-frontend/assets/96949428/d45859af-4b82-4379-871c-7f926c1b3188">

2023-12-07 01:13 UTC, dimdimah approved these changes

2023-12-07 02:51 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/tambahPaketLangganan.jsx
> +                                <div className="w-full h-56 border border-black rounded-lg flex justify-center items-center p-4">
harusnya iya, yang bikin mas charlie jadi untuk penggunaan tanya ke dia aja

2023-12-07 06:06 UTC, fannyrahmasari commented on src/pages/admin/pembayaran/editPaketLangganan.jsx
> +                                            <InputFile
oh iyaa, itu masih prevew sebelum pake input file. ini mas yang sudah di revisi

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/149cb3a6-b5de-4cc8-8c2d-b76f3e8b2d74

2023-12-07 14:12 UTC, cha-chaham approved these changes

2023-12-07 15:01 UTC, merged