feat: integrasi kelola paket langganan
HarsaEdu/harsa-frontend pull request #169
Opened 2023-12-11 13:17 UTC by fannyrahmasari

- Get data tabel kelola paket langganan 

https://github.com/HarsaEdu/harsa-frontend/assets/96949428/82902b6f-5436-4a47-9ff0-44a10d082738

2023-12-11 13:36 UTC, KokoYuardiA requested changes
sekalian add, delete, editnya mbak

2023-12-11 14:12 UTC, dimdimah approved these changes

2023-12-11 14:21 UTC, fannyrahmasari commented
> sekalian add, delete, editnya mbak

siaapppp

2023-12-12 16:17 UTC, fannyrahmasari commented
> sekalian add, delete, editnya mbak

- menambahkan fungsi integrasi  add, delete dan edit
https://drive.google.com/file/d/1ewX0SBknz77YwIyYOF_sqidKBJKxw0Uh/view?usp=sharing

2023-12-13 06:32 UTC, KokoYuardiA requested changes

2023-12-13 06:32 UTC, KokoYuardiA commented on src/pages/module/formKelasAdmin.jsx
> +<<<<<<< HEAD
coba cek yang ini mbak, kok ngepush conflict

2023-12-13 06:32 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/tambahLangganan.jsx
> +import { React, useMemo, useState, useEffect } from "react";
mungkin ganti nama filenya ke manage langganan aja

2023-12-13 06:32 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/tambahLangganan.jsx
>  const AddSubscription = () => {
ManageSubscription aja

2023-12-13 06:32 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/editPaketLangganan.jsx
> +        const response = await axios.get(
kenapa masih pakai Axios?

2023-12-13 06:39 UTC, michaelrynm approved these changes

2023-12-13 06:50 UTC, dimdimah approved these changes

2023-12-13 07:02 UTC, KokoYuardiA commented on src/pages/admin/pembayaran/editPaketLangganan.jsx
> +        const response = await axios.get(
tambahan, perbaiki validasi untuk harga di tambah paket langganan, pakai number aja

2023-12-13 12:46 UTC, fannyrahmasari commented on src/pages/admin/pembayaran/tambahLangganan.jsx
>  const AddSubscription = () => {
siapp mas

2023-12-15 00:40 UTC, KokoYuardiA approved these changes

2023-12-15 02:11 UTC, merged