slicing navbar reusable component
HarsaEdu/harsa-frontend pull request #17
Opened 2023-11-11 15:24 UTC by michaelrynm

slicing navbar reusable component

2023-11-18 14:42 UTC, KokoYuardiA requested changes
logo bisa menggunakan svg saja mas, untuk caranya jika kesulitan bisa menghubungi saya

2023-11-18 14:42 UTC, KokoYuardiA commented on src/components/ui/navbar.jsx
> +import HarsaLogo from "../../assets/HarsaLogo.png";
logo bisa menggunakan svg saja mas, untuk caranya jika kesulitan bisa menghubungi saya

2023-11-19 11:38 UTC, michaelrynm commented on src/components/ui/navbar.jsx
> +import HarsaLogo from "../../assets/HarsaLogo.png";
Sudah diganti jadi svg mas

2023-11-20 07:14 UTC, KokoYuardiA approved these changes
sudah oke

2023-11-20 07:14 UTC, merged