37 slicing landing page
HarsaEdu/harsa-frontend pull request #56
Opened 2023-11-22 14:43 UTC by michaelrynm

slicing landing page versi 6
![WhatsApp Image 2023-11-22 at 21 38 48_aa4e7b3b](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/bbb9e634-f8d3-4580-8384-2a3dbbafc2d0)
![WhatsApp Image 2023-11-22 at 21 39 11_1f359e73](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/66c26577-60c4-4f01-8b96-00669448cdd7)
![WhatsApp Image 2023-11-22 at 21 39 30_8bfa8720](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/0aac5547-3baa-4ea0-91f7-f24f511b3ea4)
![WhatsApp Image 2023-11-22 at 21 39 48_ea008371](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/e50c6f17-69f6-4560-8cd3-b6e0315b8ff4)
![WhatsApp Image 2023-11-22 at 21 40 05_8764e246](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/6d8d414e-f1bc-40dc-b0aa-5de896952f11)

2023-11-23 14:37 UTC, cha-chaham commented
Ini memang about us dan our featurenya dibiarin kecil gini ? soalnya agak beda dengan figma 
![image](https://github.com/HarsaEdu/harsa-frontend/assets/63897235/ae4f06ee-7765-4ddd-944d-3705f9557f15)

2023-11-24 14:33 UTC, michaelrynm commented
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/52728a8b-3c52-4bec-be00-d8c9cd28037e)
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/2aa2cc58-24ac-409a-8d45-a44344bdeddf)
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/6bf47eeb-50e0-4600-b66f-6753baac63f6)

**Change styling on about, feature, and testimoni card**

2023-11-24 14:45 UTC, cha-chaham approved these changes
Aku oke udah mas

2023-11-24 14:47 UTC, KokoYuardiA requested changes

2023-11-24 14:47 UTC, KokoYuardiA commented on src/pages/landing-page/aboutUs.jsx
> +                <div className="">
div imagenya pakai w5/12 aja mas

                <div className="w-5/12">
                    <img src={aboutImage} alt="image" />
                </div>

2023-11-24 14:48 UTC, NizanHulq approved these changes
Kalo dari mas charli dah aman, dri aku juga aman

2023-11-24 15:02 UTC, NizanHulq reviewed
Ada perubahan dikit di bagian button login navbar

2023-11-24 15:02 UTC, NizanHulq commented on src/components/ui/navbar.jsx
yang ini bisa pake variant dari buttonnya sebenernya
ex :
![image](https://github.com/HarsaEdu/harsa-frontend/assets/70208729/a6de44e2-eb57-4dc6-a1f0-5adcef644bb0)

2023-11-24 15:18 UTC, michaelrynm commented on src/components/ui/navbar.jsx
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/79c652f7-d3ec-4c5b-90de-46e63935905c)
Gini bener kah? Tapi hasilnya jadi gini
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/57343074-ebf7-4b9d-b5aa-942449993559)

2023-11-26 05:35 UTC, NizanHulq commented on src/components/ui/navbar.jsx
harus rebase ke dev terbaru dulu
, tapi kalau belum bisa implement ngga papa sii, lanjut aja pakai yang sebelumnya

2023-11-26 08:26 UTC, michaelrynm commented on src/components/ui/navbar.jsx
kalau gitu di bantu merge mas

2023-11-26 12:03 UTC, merged