feat: slicing edit profile page
HarsaEdu/harsa-frontend pull request #75
Opened 2023-11-28 12:20 UTC by michaelrynm

Slicing edit profile page
![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/a2d43d49-b99a-4032-a2c9-df31f40363ef)

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/975f2eee-069b-44de-8b08-ef4cb5f52b78)

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/c5fcfa7c-7a9d-4fa0-8dd4-6424d436daaf)

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/786ddf49-cca2-46bc-a53e-70d9beccb2b2)

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/41df6783-f3e7-4d91-a002-cdf3b516e02f)

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/8f4d17bb-2405-43f2-becc-14d49a10a10f)

2023-11-28 13:38 UTC, dimdimah commented
conflic nya boleh sih di resolve dulu

2023-11-28 17:53 UTC, michaelrynm commented
> Sepertinya untuk popupnya dari figma ada desain khususnya deh.. ![image](https://private-user-images.githubusercontent.com/63897235/286286712-7af93102-f124-4205-a614-1a8fd3561bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTQxNTYsIm5iZiI6MTcwMTE5Mzg1NiwicGF0aCI6Ii82Mzg5NzIzNS8yODYyODY3MTItN2FmOTMxMDItZjEyNC00MjA1LWE2MTQtMWE4ZmQzNTYxYmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE3NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzM2ZGUwMzFkYmM3YzZmMDM5NTlhYmY0ZjlhN2QzNGE2OTRhMmY2ZDU3MTIzODg4YjM4YThkODMwYzVjMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FYf18FcjxldA3xd_S_2ewslrD_HVcdnM9BSx-9J305I) apakah nanti kita buat reusablenya ?

![image](https://github.com/HarsaEdu/harsa-frontend/assets/133634767/a0b826b6-b569-4e0f-89de-7f7c97de346b)
figma nya tidak konsisten
baiknya gimana ini

2023-11-28 17:54 UTC, michaelrynm commented
> conflic nya boleh sih di resolve dulu

oke siap mas

2023-11-29 05:45 UTC, KokoYuardiA requested changes
Desain Alert ngikutin yang di halaman final design figma ya

2023-11-29 15:47 UTC, NizanHulq reviewed
Aman mass

2023-12-02 05:17 UTC, merged